### ISSUE TITLE
Wrong attribute name in sample

### ISSUE THREAD

**Issue by vankooch** [npgsql/npgsql.github.io#9]
Hi,
in the documentation page for "_Enums and Composites_" at "_Name Translation_" section, there is a wrong attribute name in the sample.

Sample says:
**[PgLabel("happy")]**

This should be:
**[PgName("happy")]**

The attribute PgLabel does not exist. In the description text just before the sample the name of the attribute is correct (PgName).
Also it would be better if you could set the full-name of the attribute, including namespace. 
Like:
**[NpgsqlTypes.PgName("happy")]**

Best regards & thanks

**Comment by roji** [comment]
Thanks, have corrected this.
